name: CI/CD Pipeline with Security

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker Image
      run: docker build -t myapp:latest .

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@0.50.0
      with:
        image-ref: 'docker.io/my-organization/my-app:${{ github.sha }}'
        format: 'sarif'
        output: 'trivy-results.sarif'

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: 'trivy-results.sarif'

    - name: Push Docker Image
      run: docker push myapp:latest
      if: success()
