name: CI/CD Pipeline with Security

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

    - name: Build Docker Image
      run: docker build -t myapp:latest .

    - name: Run Security Scan with Trivy
      uses: aquasecurity/trivy-action@v0.2.0
      with:
        image-ref: myapp:latest
        format: 'table'
        exit-code: '0'
        severity: 'HIGH,CRITICAL'

    - name: Push Docker Image
      run: docker push myapp:latest
      if: success()
