name: CI

on: [push]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Scan for vulnerabilities
        uses: aquasecurity/trivy-action@v0.5.0
        with:
          image-ref: 'YOUR_DOCKER_IMAGE:YOUR_TAG'

